pipeline {
    agent any
    
    triggers {
        githubPush()
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                dir('demo') {
                    sh './gradlew clean build'
                }
            }
        }

        stage('Package') {
            steps {
                dir('demo') {
                    sh './gradlew bootJar'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('demo') {
                    sh './scripts/deploy.sh'
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'demo/build/libs/*.jar', fingerprint: true
        }
    }
}